import os
from dotenv import load_dotenv
from azure.cosmos import CosmosClient, PartitionKey
from datetime import datetime

load_dotenv()

COSMOS_CONN_STR = os.getenv("COSMO_DB_CONNECTION_STRING")
COSMOS_DB_NAME = os.getenv("COSMO_DB_NAME", "talk2data")
COSMOS_CONTAINER_NAME = os.getenv("COSMO_DB_CONTAINER", "conversations")

client = CosmosClient.from_connection_string(COSMOS_CONN_STR)
database = client.create_database_if_not_exists(id=COSMOS_DB_NAME)
container = database.create_container_if_not_exists(
    id=COSMOS_CONTAINER_NAME,
    partition_key=PartitionKey(path="/sessionID")
)

def add_request_response(session_id, request_text, response_text, request_time=None, response_time=None):
    """Add a request/response pair to the session in CosmosDB."""
    print(f"[DEBUG] add_request_response called with session_id={session_id}, request_text={request_text}, response_text={response_text}")
    request_time = request_time or datetime.utcnow().strftime("%H:%M:%S UTC")
    response_time = response_time or datetime.utcnow().strftime("%H:%M:%S UTC")
    # Try to fetch the session doc
    session = get_session(session_id)
    if session is None:
        session = {
            "id": session_id,
            "sessionID": session_id,
            "request": [],
            "response": []
        }
    session["request"].append({"text": request_text, "time": request_time})
    session["response"].append({"text": response_text, "time": response_time})
    try:
        container.upsert_item(session)
        print(f"[DEBUG] Successfully upserted session: {session_id}")
    except Exception as e:
        print(f"[ERROR] Failed to upsert session in CosmosDB: {e}")


def get_last_n_pairs(session_id, n=10):
    """Get the last n request/response pairs for a session."""
    session = get_session(session_id)
    if session is None:
        return []
    reqs = session.get("request", [])[-n:]
    resps = session.get("response", [])[-n:]
    return list(zip(reqs, resps))


def get_session(session_id):
    """Fetch the session document by sessionID."""
    query = f"SELECT * FROM c WHERE c.sessionID = @sessionID"
    params = [{"name": "@sessionID", "value": session_id}]
    items = list(container.query_items(query=query, parameters=params, enable_cross_partition_query=True))
    return items[0] if items else None

def add_interaction(
    session_id,
    user_request,
    llm_sql_response,
    sql_db_response,
    summary_request,
    summary_response,
    time=None
):
    """
    Store a full interaction in CosmosDB for the given session_id.
    Each interaction includes:
      - USER_REQUEST: The user's natural language query
      - LLM_SQL_RESPONSE: The SQL generated by the LLM
      - SQL_DB_RESPONSE: The result of executing the SQL on the database
      - SUMMARY_REQUEST: The prompt/request sent to the LLM for summary
      - SUMMARY_RESPONSE: The summary generated by the LLM
    All interactions are stored in the 'interactions' array in the session document.
    """
    time = time or datetime.utcnow().strftime("%H:%M:%S UTC")
    session = get_session(session_id)
    if session is None:
        session = {
            "id": session_id,
            "sessionID": session_id,
            "interactions": []
        }
    else:
        # Initialize interactions array if it doesn't exist
        if "interactions" not in session:
            session["interactions"] = []
            
    session["interactions"].append({
        "USER_REQUEST": user_request,
        "LLM_SQL_RESPONSE": llm_sql_response,
        "SQL_DB_RESPONSE": sql_db_response,
        "SUMMARY_REQUEST": summary_request,
        "SUMMARY_RESPONSE": summary_response,
        "time": time
    })
    try:
        container.upsert_item(session)
        print(f"[DEBUG] Successfully upserted session: {session_id}")
    except Exception as e:
        print(f"[ERROR] Failed to upsert session in CosmosDB: {e}") 